version: '3.8'

services:
  # PHP-FPM Application Service
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: reservation_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:1.19-alpine
    container_name: reservation_nginx
    restart: unless-stopped
    ports:
      - "8000:80" # El puerto 8000 de tu máquina se conecta al 80 del contenedor
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: reservation_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-reservations_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_USER: ${DB_USERNAME:-user}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3307}:3307"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local